-- MySQL Script generated by MySQL Workbench
-- Tue Nov  8 08:12:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OficinaDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OficinaDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OficinaDB` DEFAULT CHARACTER SET utf8 ;
USE `OficinaDB` ;

-- -----------------------------------------------------
-- Table `OficinaDB`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OficinaDB`.`Clientes` (
  `idClientes` INT NOT NULL,
  `Nome` VARCHAR(60) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `Numero_Endereco` INT NOT NULL,
  `Complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`idClientes`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OficinaDB`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OficinaDB`.`Veiculo` (
  `idVeiculo` INT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  `Placa` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVeiculo`),
  INDEX `fk_Veiculo_Clientes_idx` (`Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Clientes`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `OficinaDB`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OficinaDB`.`Mecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OficinaDB`.`Mecanicos` (
  `idMecanicos` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Area_Atuacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMecanicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OficinaDB`.`Equipe_Mecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OficinaDB`.`Equipe_Mecanicos` (
  `idEquipe_Mecanicos` INT NOT NULL,
  `Coordernador_Equipe_idMecanicos` INT NOT NULL,
  `Tipo_Equipe` VARCHAR(45) NOT NULL,
  `Status_Equipe` ENUM('Operante', 'Ocupada', 'Não Operante') NOT NULL DEFAULT 'Operante',
  PRIMARY KEY (`idEquipe_Mecanicos`),
  INDEX `fk_Equipe_Mecanicos_Mecanicos1_idx` (`Coordernador_Equipe_idMecanicos` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_Mecanicos_Mecanicos1`
    FOREIGN KEY (`Coordernador_Equipe_idMecanicos`)
    REFERENCES `OficinaDB`.`Mecanicos` (`idMecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OficinaDB`.`Ordem_Servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OficinaDB`.`Ordem_Servicos` (
  `idOrdem_Servicos` INT NOT NULL,
  `Equipe_Mecanicos_idEquipe_Mecanicos` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Data_Entrega_Prevista` DATE NOT NULL,
  `Data_Emissao` DATE NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Validacao_Cliente_Status` ENUM('À Validar', 'Validado', 'Cancelado') NOT NULL DEFAULT 'À Validar',
  PRIMARY KEY (`idOrdem_Servicos`),
  INDEX `fk_Ordem_Servicos_Equipe_Mecanicos1_idx` (`Equipe_Mecanicos_idEquipe_Mecanicos` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_Servicos_Equipe_Mecanicos1`
    FOREIGN KEY (`Equipe_Mecanicos_idEquipe_Mecanicos`)
    REFERENCES `OficinaDB`.`Equipe_Mecanicos` (`idEquipe_Mecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OficinaDB`.`Pecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OficinaDB`.`Pecas` (
  `idPecas` INT NOT NULL,
  `Nome_Peca` VARCHAR(45) NOT NULL,
  `Custo` FLOAT NOT NULL,
  PRIMARY KEY (`idPecas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OficinaDB`.`Servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OficinaDB`.`Servicos` (
  `idServicos` INT NOT NULL,
  `Tipo_Servico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idServicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OficinaDB`.`Composicao_Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OficinaDB`.`Composicao_Equipe` (
  `Equipe_Mecanicos_idEquipe_Mecanicos` INT NOT NULL,
  `Mecanicos_idMecanicos` INT NOT NULL,
  PRIMARY KEY (`Equipe_Mecanicos_idEquipe_Mecanicos`, `Mecanicos_idMecanicos`),
  INDEX `fk_Equipe_Mecanicos_has_Mecanicos_Mecanicos1_idx` (`Mecanicos_idMecanicos` ASC) VISIBLE,
  INDEX `fk_Equipe_Mecanicos_has_Mecanicos_Equipe_Mecanicos1_idx` (`Equipe_Mecanicos_idEquipe_Mecanicos` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_Mecanicos_has_Mecanicos_Equipe_Mecanicos1`
    FOREIGN KEY (`Equipe_Mecanicos_idEquipe_Mecanicos`)
    REFERENCES `OficinaDB`.`Equipe_Mecanicos` (`idEquipe_Mecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe_Mecanicos_has_Mecanicos_Mecanicos1`
    FOREIGN KEY (`Mecanicos_idMecanicos`)
    REFERENCES `OficinaDB`.`Mecanicos` (`idMecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OficinaDB`.`Vistoria_Veiculo_Por_Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OficinaDB`.`Vistoria_Veiculo_Por_Equipe` (
  `Equipe_Mecanicos_idEquipe_Mecanicos` INT NOT NULL,
  `Veiculo_idVeiculo` INT NOT NULL,
  `Data_Vistoria` DATE NOT NULL,
  `Status` ENUM('Quebrado', 'Reparo', 'Checagem') NOT NULL,
  PRIMARY KEY (`Equipe_Mecanicos_idEquipe_Mecanicos`, `Veiculo_idVeiculo`),
  INDEX `fk_Equipe_Mecanicos_has_Veiculo_Veiculo1_idx` (`Veiculo_idVeiculo` ASC) VISIBLE,
  INDEX `fk_Equipe_Mecanicos_has_Veiculo_Equipe_Mecanicos1_idx` (`Equipe_Mecanicos_idEquipe_Mecanicos` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_Mecanicos_has_Veiculo_Equipe_Mecanicos1`
    FOREIGN KEY (`Equipe_Mecanicos_idEquipe_Mecanicos`)
    REFERENCES `OficinaDB`.`Equipe_Mecanicos` (`idEquipe_Mecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe_Mecanicos_has_Veiculo_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo`)
    REFERENCES `OficinaDB`.`Veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OficinaDB`.`Servicos_Incluidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OficinaDB`.`Servicos_Incluidos` (
  `Ordem_Servicos_idOrdem_Servicos` INT NOT NULL,
  `Servicos_idServicos` INT NOT NULL,
  PRIMARY KEY (`Ordem_Servicos_idOrdem_Servicos`, `Servicos_idServicos`),
  INDEX `fk_Ordem_Servicos_has_Servicos_Servicos1_idx` (`Servicos_idServicos` ASC) VISIBLE,
  INDEX `fk_Ordem_Servicos_has_Servicos_Ordem_Servicos1_idx` (`Ordem_Servicos_idOrdem_Servicos` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_Servicos_has_Servicos_Ordem_Servicos1`
    FOREIGN KEY (`Ordem_Servicos_idOrdem_Servicos`)
    REFERENCES `OficinaDB`.`Ordem_Servicos` (`idOrdem_Servicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_Servicos_has_Servicos_Servicos1`
    FOREIGN KEY (`Servicos_idServicos`)
    REFERENCES `OficinaDB`.`Servicos` (`idServicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OficinaDB`.`Pecas_Por_Os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OficinaDB`.`Pecas_Por_Os` (
  `Ordem_Servicos_idOrdem_Servicos` INT NOT NULL,
  `Pecas_idPecas` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Ordem_Servicos_idOrdem_Servicos`, `Pecas_idPecas`),
  INDEX `fk_Ordem_Servicos_has_Pecas_Pecas1_idx` (`Pecas_idPecas` ASC) VISIBLE,
  INDEX `fk_Ordem_Servicos_has_Pecas_Ordem_Servicos1_idx` (`Ordem_Servicos_idOrdem_Servicos` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_Servicos_has_Pecas_Ordem_Servicos1`
    FOREIGN KEY (`Ordem_Servicos_idOrdem_Servicos`)
    REFERENCES `OficinaDB`.`Ordem_Servicos` (`idOrdem_Servicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_Servicos_has_Pecas_Pecas1`
    FOREIGN KEY (`Pecas_idPecas`)
    REFERENCES `OficinaDB`.`Pecas` (`idPecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
